name: Nix Flake actions

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - 'releases/**'
  workflow_dispatch:

jobs:
  nix-init:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        # with: 
        #   install_url: https://install.lix.systems/lix
        #   install_options: install --no-confirm
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json -f ./ci/workflows.nix)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        # with: 
        #   install_url: https://install.lix.systems/lix
        #   install_options: install --no-confirm
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - id: build-all-nix
        name: Build Nix packages
        run: |
          set -Eeu
          
          nix build -L -f ci/build-all-nix.nix _allPackages -o result-allNix

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: [nix-init, nix-prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-init.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        # with:
        #   install_url: https://install.lix.systems/lix
        #   install_options: install --no-confirm
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build -L -f '${{ matrix.file }}' '${{ matrix.attr }}'
